version: '3'

services:

    app:
        build: ./docker/php-8.2
        container_name: microservice-videos-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-php-entrypoint
        command: bash -c "composer install --working-dir=/var/www && php /var/www/artisan migrate --seed && php-fpm"
        volumes:
            - .:/var/www
        networks:
            - app-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - db
            - redis

    nginx:
        build: ./docker/nginx
        container_name: microservice-videos-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        image: mysql:8
        container_name: microservice-videos-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=code_micro_videos
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: microservice-videos-redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
